package com.example.twitterfalso.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF1DA1F2)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCFE5FF)
val onPrimaryContainerLight = Color(0xFF114A73)
val secondaryLight = Color(0xFF126682)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBDE9FF)
val onSecondaryContainerLight = Color(0xFF004D64)
val tertiaryLight = Color(0xFF1D6586)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC4E7FF)
val onTertiaryContainerLight = Color(0xFF004C69)
val errorLight = Color(0xFF904A43)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD5)
val onErrorContainerLight = Color(0xFF73342D)
val backgroundLight = Color(0xFFFDFDFD)
val onBackgroundLight = Color(0xFF181C20)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDEE3EB)
val onSurfaceVariantLight = Color(0xFF42474E)
val outlineLight = Color(0xFFBDB6B6)
val outlineVariantLight = Color(0xFFC2C7CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF9CCBFB)
val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryDark = Color(0xFF9CCBFB)
val onPrimaryDark = Color(0xFF003354)
val primaryContainerDark = Color(0xFF114A73)
val onPrimaryContainerDark = Color(0xFFCFE5FF)
val secondaryDark = Color(0xFF8BD0EF)
val onSecondaryDark = Color(0xFF003546)
val secondaryContainerDark = Color(0xFF004D64)
val onSecondaryContainerDark = Color(0xFFBDE9FF)
val tertiaryDark = Color(0xFF90CEF4)
val onTertiaryDark = Color(0xFF00344A)
val tertiaryContainerDark = Color(0xFF004C69)
val onTertiaryContainerDark = Color(0xFFC4E7FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF561E19)
val errorContainerDark = Color(0xFF73342D)
val onErrorContainerDark = Color(0xFFFFDAD5)
val backgroundDark = Color(0xFF101418)
val onBackgroundDark = Color(0xFFE0E2E8)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF42474E)
val onSurfaceVariantDark = Color(0xFFC2C7CF)
val outlineDark = Color(0xFF8C9199)
val outlineVariantDark = Color(0xFF42474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF31628D)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)


